language: node_js
node_js:
  - node

dist: bionic
sudo: required

notifications:
  email:
    recipients:
      - bunnyppl@gmail.com
    on_success: always
    on_failure: always
branches:
  only:
    - development
before_script:
  - npm install -g @angular/cli
  - npm install -g now
script:
  - ng build --prod --base-href https://chrismintan.github.io/bitcoin-order-app/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: 1bbf0b73e7011e0632ceccc32d840755d68196f1
  local_dir: dist/bitcoin
  on:
    branch: development
